baseURL = 'https://romka.eu/'
languageCode = 'en-us'
title = 'Romka!eu'
summaryLength = 25
copyright = "Roman Arkharov - All rights reserved"
theme = 'fruhling'
defaultcontentlanguage = 'ru'
languagecode = "ru-ru"
enableRobotsTXT = true
googleAnalytics = "G-CTT4LY4QD1"
timeout = "1800s"
relativeURLs = true

[markup.goldmark.renderer]
    unsafe= true

[outputs]
    page = ["html"]
    section = ["html"]
    term = ["html"]
    home = ["html"]

[params]
    remark_enabled = true
    remark_url = "https://romka.eu/remark42"
    remark_site_id = "romkaeu"
    robots_txt_disallow_all = false