services:
  - type: web
    name: romka-eu
    runtime: static
    buildCommand: chmod a+x render-build.sh && ./render-build.sh
    staticPublishPath: public
    envVars:
      - key: HUGO_VERSION
        value: 0.163.3
